[tool.poetry]
name = "flastream"
version = "0.1.0"
description = ""
authors = ["subhamivan <ivan.sarangi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
